### ISSUE TITLE
자바 기반 애플리케이션에서 기호 입력

### ISSUE THREAD

**Issue by nacyot** [hatemogi/AewolInput#4]
안녕하세요!

드보락 사용자인데, 덕분에 애월 입력기 잘 쓰고 있습니다. 다름이 아니라 요세미티에서 애월 입력기(0.1.5)를 사용하는 도중에 문제가 있어 이슈로 올려봅니다. 이번에 고쳐진 스페이스 문제와 마찬가지로 자바 기반 애플리케이션에서 기호 입력할 때 문제가 조금 있습니다. 저는 영어 Dvorak 자판과 애월 입력기를 사용하는데, 자바 기반 애플리케이션에서는 애월 입력기 상태에서 ,.를 입력할 때 원래 드보락 자판인 wv이 입력됩니다. 다른 기호들도 마찬가지로 한글 자판의 기호인 -=[]이 드보락 자판 기호인 []/=로 입력됩니다. 한글은 제대로 처리가 되는데 기호은 투명하게 넘겨지는 듯 합니다.

네이티브 앱에서는 발생하지 않고, 파이참, OmegaT와 같은 자바 기반 애플리케이션에서만 그런 듯 합니다.

**Comment by hatemogi** [comment]
와 안녕하세요, 저말고 애월입력기를 쓰고 계시는 분이 있으시다니, 감사할따름입니다. 말씀하신 문제는 자바기반 애플리케이션에서 쿼티특수키부분을 누를 때의 문제를 말씀하시는 것 같습니다. 죄송하게도, 이 문제는 해결이 어려울 것 같습니다.

**Comment by hatemogi** [comment]
고마운 마음에, 다시 한번 도전해 봤습니다만, 결론부터 말씀드리자면, 문제 해결을 포기합니다. 증상 확인과 재현이 가능하나, 해결안을 모르겠습니다.

혹시 관심있으실까봐 구차한 변명을 덧붙이겠습니다. (짧게 요약하면, "이만큼 알아봤으나 더는 모르겠다. 그러니 이해해달라." 뭐 이런 말씀이 되겠네요 ㅠ)

정확한 내용은 모르겠지만, 관련한 이슈는 JetBrains사의 애플리케이션들이 돌아가는 자바AWT 환경에서 발생하는 것 같습니다. 이 문제 상황과 일치하는 내용인지 불확실하나, 흔히 발견되는 문제라, 그쪽 [이슈트래커](https://youtrack.jetbrains.com/issue/IDEA-63779)에서처럼 종종 언급되는 골칫거리인듯 합니다. 사실 OSX와 오라클이 해결해줘야할 문제로 보이는데, AWT가 레거시이기도 해서인지, 앞으로도 원만히 해결될 문제로 보이지는 않습니다. 

<img width="562" alt="2016-01-05 4 13 03" src="https://cloud.githubusercontent.com/assets/238582/12114499/b0c65dde-b3ed-11e5-94e9-f251bdbe366d.png">

애월입력기의 디버그 모드를 켜놓으면, 키 전송에 관련한 콘솔로그를 찍을 수 있습니다. 콘솔 앱에서 확인 가능한데요, 위 로그는 '''김대현...'''을 입력했을 때의 로그이고,  인텔리J에서는 '''김대현.vv''' 로 입력됩니다. 분명 '''.'''을 문자열로 보냈는데, 무시하고, 시스템의 그 다음 입력기의 값을 쓰는 것 같습니다.

참고로, OS X의 시스템 API들이 초기에는 C버전으로만 나오고 (Carbon), 많이 쓰이는 일반적(?) 라이브러리가 되면, Obj-C(요새는 물론 Swift까지요)로 쓰기 좋은 레이어가 올라가는 수순으로 보이는데, 제가 쓴 API도, Obj-C 레이어에 있는 InputMethodKit을 썼습니다. 어쩌면, Carbon API를 건드려서 문제 상황을 우회할 수 있을지도 모르겠다는 추측이 들기는 합니다. 아쉽지만, 그렇게까지 해가며 해결할 여력(의지)는 없구요.

혹시, @nacyot 님뿐 아니라, 이 이슈를 보시는 누군가가 또 다른 해결책을 귀뜸해주시면 다시 도전해 볼지도 모르겠습니다.

가장 좋은 것은, 아예 해결도 해서 풀리퀘스트를 날려주시는 것인데, 아무래도 그건 기대하지 않는 게 좋겠죠. ^^ 
 
유쾌한 답변을 드리지 못했지만, 그래도 써주시고, 이슈까지 남겨주셔서 고맙습니다. 저말고도 한 분 더 쓰시는 걸로 알게 되었네요. :smile:

**Comment by nacyot** [comment]
드보락, 두벌식으로 쓰다보니 항상 고난이 많은데, 애월 입력기 덕을 톡톡히 보고 있습니다. 제가 익숙치 않은 분야라 당장은 도움 드릴 게 없지만 저도 기회 되면 살펴보도록 하겠습니다. 

신경써 주셔서 감사합니다!
